# Generated by Django 5.2.1 on 2025-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                default="Россия", help_text="Укажите страну проживания", max_length=30, verbose_name="Страна"
            ),
        ),
    ]
