# Generated by Django 5.2.1 on 2025-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Введите заголовок", max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(help_text="Введите содержание", verbose_name="Содержание")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите фото(изображение)",
                        null=True,
                        upload_to="post/preview",
                        verbose_name="Превью(изображение)",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("publication_sign", models.BooleanField(default=False, verbose_name="Признак публикации")),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "записи",
            },
        ),
    ]
