# Generated by Django 4.2.2 on 2025-07-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_delete_product", "Can delete product"),
                ],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("review", "На модерации"),
                    ("published", "Опубликован"),
                    ("hidden", "Скрыт"),
                ],
                default="draft",
                help_text="Текущий статус публикации продукта",
                max_length=10,
                verbose_name="Статус публикации",
            ),
        ),
    ]
